Portfolio: desktop version
SoniaKarungi/Portfolio pull request #4
Opened 2022-03-24 12:00 UTC by SoniaKarungi

- Use media queries in CSS file to make the desktop version look like the template I selected (Desktop: 768px or wider).
- Use Grid and Flexbox to lay out the elements.

2022-03-24 13:10 UTC, ShadyShawkat requested changes
## Hi @SoniaKarungi, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 13:10 UTC, ShadyShawkat commented on index.html
>              <ul class="languages skills-list">
- [x] Kindly change the bullet points' positioning in the mobile version to match the Figma design.
- [x] Please remove the extra spacing on both sides of this section to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/159916505-2da658ab-9129-41ee-b608-67b6bd3cb1f7.png) | ![image](https://user-images.githubusercontent.com/62290545/159918731-adacf271-9d88-4cb1-b5b2-3182d44191c8.png) |

2022-03-24 13:10 UTC, ShadyShawkat commented on index.html
> +      <form action="https://formspree.io/f/mayvbgrw" method="POST">
- Kindly try to match the Figma design as much as possible, which includes:
   - [x] Adjusting the spacing around each element to match the Figma design.
   - [x] Using the same font style (family, color, size, ...etc) as the Figma design.
   - [x] Adjusting elements' widths (like your form's width) to be more like the Figma design.
   - [x] Increasing the space between the social media links to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/159917581-5b7b405a-ecc8-43b6-b120-d418759d559e.png) | ![image](https://user-images.githubusercontent.com/62290545/159917516-69308331-f293-4962-aec9-94eef64b9f7f.png) |

2022-03-24 13:10 UTC, ShadyShawkat commented on index.html
> +      </div>
- [x] Kindly increase the top spacing above this section's social links to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/159919413-889af6f3-59ad-42f9-98dc-aaead8f2bf24.png) | ![image](https://user-images.githubusercontent.com/62290545/159919888-09cf3d93-253b-4943-a2c5-02e0bb30e2be.png) |

2022-03-24 13:10 UTC, ShadyShawkat commented on index.html
> +        <hr class="recent-works-line">
- [x] [OPTIONAL] Kindly try to use only one `h1` tag in the whole web page. This is considered good practice and is more professional. You can use other heading tags depending on the hierarchy of your headings in the web page.
- [x] Kindly increase this horizontal line's length to match the Figma design.
- [x] Please increase the left and right spacing of the works section

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/159920199-1f72746f-6b4b-4014-991d-3e982af2ba63.png) | ![image](https://user-images.githubusercontent.com/62290545/159920258-73a5eab5-58b7-49a4-9283-af917f9208fd.png) |

2022-03-24 13:10 UTC, ShadyShawkat commented on index.html
>              Hello I’m a software developer! I can help you build a product ,
- [x] Kindly adjust the spacing in this section to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/159920718-3f1b495b-dda3-4261-a2c7-507cf26dae09.png) | ![image](https://user-images.githubusercontent.com/62290545/159920791-afae2363-69f9-4e31-8dfe-e47f7b9de043.png) |

2022-03-24 13:10 UTC, ShadyShawkat commented on index.html
>              <ul class="languages skills-list">
- [x] Kindly try to make this section take the whole width to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/159921160-fc19cfdd-2e69-4287-a7fb-b0de0be5b540.png) | ![image](https://user-images.githubusercontent.com/62290545/159921205-72715672-58cf-4852-8553-04ffbfa90f9a.png) |

2022-03-24 13:10 UTC, ShadyShawkat commented on index.html
>            name="name"
- Kindly try to stick as much as possible to the Figma design, which includes:
   - [ ] Adjusting the spacing around this section to match the Figma design.
   - [ ] Using the same font style from the Figma design.
   - [ ] Adding a horizontal line above the social media icons.
   - [ ] Adjusting the width of the "Get in touch" button's width to match the Figma design.

| Your design | Figma design | 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/159921788-c1594ecb-c8b1-4ef4-b1bd-09931f686f2a.png) | ![image](https://user-images.githubusercontent.com/62290545/159921909-85790cda-533d-4d26-8dd3-d4049efc4457.png) |

2022-03-24 15:17 UTC, SoniaKarungi commented on index.html
>              <ul class="languages skills-list">
Was a tricky one but I think I finally did it! Thanks for all the feedback. Working on it.

2022-03-24 16:45 UTC, gemmen29 requested changes
Hi @SoniaKarungi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 16:45 UTC, gemmen29 commented on index.html
> +          <h2 class="about-me">About me</h2>
Kindly adjust the spacing in the about section as the previous reviewer asked.
| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/159966907-fbf751e5-501e-450f-baf3-3b36418f0ecc.png) | ![image](https://user-images.githubusercontent.com/24703171/159966538-93f3b4e5-36eb-4360-a7a1-211cb16dd0df.png) |

2022-03-25 05:05 UTC, FrederickMih approved these changes
# Status : Approved :tada: 
![133696300-b506e476-dc1a-443e-935a-c6f434e788b6](https://user-images.githubusercontent.com/63087491/160057962-f7e475f1-2a8e-4528-86bb-1303cddb6b18.jpg)


Hi @SoniaKarungi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 10:09 UTC, merged